import { prisma } from '@/backend/infrastructure/database/client';
import { callAI } from './ai.service';
import { NavService } from './NavService';
import { PortfolioService } from './PortfolioService';
import { CacheManager } from '@/backend/infrastructure/redis/cache/CacheManager';
import { logger } from '@/lib/logger';

export class AIRecommendationService {
  private portfolioService = new PortfolioService();

  async getGoalRecommendations(goalId: string, userId: string) {
    return prisma.aIRecommendation.findMany({
      where: { goalId, userId },
      orderBy: { score: 'desc' }
    });
  }

  async generateRecommendations(userId: string, goalId: string) {
    // 1. Rate limiting check (5 reqs / hour / user)
    const rateLimitKey = `ratelimit:ai_recommend:${userId}`;
    const requestsCount = await CacheManager.get<number>(rateLimitKey) || 0;
    if (requestsCount >= 5) {
      throw new Error('Rate limit exceeded: You can only generate recommendations 5 times per hour.');
    }

    const goal = await prisma.goal.findUnique({ where: { id: goalId, userId } });
    if (!goal) throw new Error('Goal not found');

    const portfolio = await this.portfolioService.getPortfolio(userId);
    const existingHoldings = portfolio?.holdings.map(h => `${h.fundName} (${h.category})`).join(', ') || 'None';

    const prompt = `
You are an expert AI financial advisor. Based on the following context, recommend 4 to 6 specific mutual funds available in India that perfectly match the user's goal.
DO NOT invent funds. Use real, well-known mutual funds in India.
CRITICAL RULES:
1. ONLY recommend "Direct Growth" variants. NEVER recommend "IDCW", "Dividend", or "Regular" plans.
2. Strictly respect the user's risk appetite: low -> debt/hybrid/large-cap, high -> mid/small/flexi/thematic.
3. Time horizon must dictate equity allocation. Short term (<3 years) should be mostly debt/liquid.
4. Score MUST be a number between 0 and 100 representing the match percentage. Do not use percentages like 9500.
5. ONLY recommend currently active and accepting-investment mutual funds. NEVER recommend closed, merged, or terminated funds.

Context:
- Goal Type: ${goal.goalType}
- Investment Type: ${goal.investmentType}
- Lumpsum Amount: ₹${goal.lumpsumAmount || 0}
- SIP Amount: ₹${goal.sipAmount || 0}
- Target Corpus: ₹${goal.targetAmount || 'Not specified'}
- Time Horizon: ${goal.timeHorizonYears} years (Flexible: ${goal.isFlexibleHorizon})
- Risk Appetite: ${goal.riskAppetite}
- User Age: ${goal.age}
- Additional Notes: ${goal.additionalNotes || 'None'}
- User's Current Portfolio Holdings: ${existingHoldings}

Respond strictly with this JSON format. No markdown, no explanations outside JSON.
{
  "recommendations": [
    {
      "schemeCode": "122639 (Provide a real AMFI scheme code if known, or leave empty string if unsure)",
      "fundName": "Exact name of the fund (e.g. Parag Parikh Flexi Cap Fund Direct Growth)",
      "category": "Fund Category",
      "score": 95,
      "reason": "Why this fund fits the goal",
      "suggestedAllocationPercent": 25
    }
  ]
}
`;

    const responseText = await callAI(prompt, 'json');
    let aiRecs: any;
    try {
      aiRecs = JSON.parse(responseText);
    } catch (e) {
      logger.error(`AI returned invalid JSON: ${responseText}`);
      throw new Error('AI returned an invalid format. Please try again.');
    }

    const recommendations = aiRecs.recommendations || [];
    if (!Array.isArray(recommendations) || recommendations.length === 0) {
      throw new Error('No recommendations generated by AI.');
    }

    // Clear old AI recommendations for this goal
    await prisma.aIRecommendation.deleteMany({ where: { goalId: goal.id } });

    // Validate with NavService/AMFI and save
    const savedRecs = [];
    let totalAlloc = 0;
    const processedSchemeCodes = new Set<string>();

    for (const rec of recommendations) {
      let validSchemeCode = rec.schemeCode;
      let validFundName = rec.fundName;
      let validCategory = rec.category;

      // Try validating the provided schemeCode, or search universe if needed
      // Actually, searching text in AMFI universe is complex, but we can do a quick check
      if (validSchemeCode) {
        const liveNav = await NavService.getLatestNav(validSchemeCode);
        if (!liveNav.navUnavailable) {
          validFundName = liveNav.schemeName || validFundName;
          validCategory = liveNav.category || validCategory;
        } else {
          validSchemeCode = ''; // invalid scheme code
        }
      }

      // If no valid scheme code provided by AI, try searching AMFI universe by name
      if (!validSchemeCode) {
        const universeCacheKey = 'amfi:universe:parsed';
        const universe = await CacheManager.get<Record<string, any>>(universeCacheKey);
        if (universe) {
          const matched = Object.values(universe).find((f: any) => 
            f.schemeName.toLowerCase().includes(rec.fundName.toLowerCase().replace('direct', '').replace('growth', '').trim())
          );
          if (matched) {
            validSchemeCode = matched.schemeCode;
            validFundName = matched.schemeName;
            validCategory = matched.category;
          }
        }
      }

      // Only save if we found a valid scheme code (or at least we keep what the AI gave if it looks like a string, but user wanted validation if possible)
      // If we still can't find a valid scheme code, we might fallback to generic name, but for a real app we want real codes.
      // Let's just save it; if schemeCode is empty, the UI can disable "Add to Portfolio"
      
      // Validation: Filter out non-Direct Growth if we can tell from the name
      const lowerName = validFundName.toLowerCase();
      if (lowerName.includes('idcw') || lowerName.includes('dividend') || lowerName.includes('regular')) {
        continue; // Skip this recommendation completely
      }

      // Normalize score between 0 and 100
      let normalizedScore = Number(rec.score);
      if (isNaN(normalizedScore)) normalizedScore = 80;
      if (normalizedScore > 100 && normalizedScore <= 10000) normalizedScore = normalizedScore / 100; // e.g. 9500 -> 95
      normalizedScore = Math.min(100, Math.max(0, normalizedScore));

      // Skip duplicate scheme codes
      if (validSchemeCode && processedSchemeCodes.has(validSchemeCode)) {
        continue;
      }
      if (validSchemeCode) {
        processedSchemeCodes.add(validSchemeCode);
      }

      const saved = await prisma.aIRecommendation.create({
        data: {
          goalId: goal.id,
          userId,
          schemeCode: validSchemeCode || '',
          fundName: validFundName,
          category: validCategory,
          score: normalizedScore,
          reason: rec.reason || 'Recommended by AI',
          suggestedAllocationPercent: rec.suggestedAllocationPercent || 0
        }
      });
      savedRecs.push(saved);
      totalAlloc += (rec.suggestedAllocationPercent || 0);
    }

    // Increment rate limit counter
    await CacheManager.set(rateLimitKey, requestsCount + 1, 3600); // 1 hour TTL

    return savedRecs.sort((a, b) => b.score - a.score);
  }
}
